spring.application.name=loan

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/loan_db
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# App Port
server.port=8081

# Iwomi payment gateway
payment.gateway.base-url=${PAYMENT_GATEWAY_BASE_URL:https://www.pay.iwomitechnologies.com/api/iwomipay_sandbox}
payment.gateway.username=${PAYMENT_GATEWAY_USERNAME}
payment.gateway.password=${PAYMENT_GATEWAY_PASSWORD}
payment.gateway.types.momo.api-key=${IWOMI_MOMO_API_KEY}
payment.gateway.types.momo.api-secret=${IWOMI_MOMO_API_SECRET}
payment.gateway.types.om.api-key=${IWOMI_OM_API_KEY}
payment.gateway.types.om.api-secret=${IWOMI_OM_API_SECRET}